"""Add reading_time to posts and user profile fields

Revision ID: 84c25e0c8f7d
Revises: 4adb061eacfa
Create Date: 2025-09-17 18:00:22.372766

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84c25e0c8f7d"
down_revision: Union[str, Sequence[str], None] = "4adb061eacfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


userposition_enum = sa.Enum(
    "FRONTEND",
    "BACKEND",
    "FULLSTACK",
    "DEVOPS",
    "MOBILE",
    "DATA",
    "DESIGN",
    "OTHER",
    name="userposition",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    userposition_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("posts", sa.Column("reading_time", sa.Integer(), nullable=False))
    op.add_column(
        "users", sa.Column("description", sa.String(length=500), nullable=True)
    )
    op.add_column("users", sa.Column("position", userposition_enum, nullable=True))
    op.add_column("users", sa.Column("stack", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "stack")
    op.drop_column("users", "position")
    op.drop_column("users", "description")
    op.drop_column("posts", "reading_time")
    # ### end Alembic commands ###
